spring.application.name=sistema-subastas

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}

# En producción, spring.jpa.hibernate.ddl-auto debe estar en validate
# para evitar que Hibernate modifique automáticamente el esquema de la base de datos.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true